@hostname = 127.0.0.1
@port = 3000
@serverUrl = http://{{hostname}}:{{port}} 
@baseUrl = http://{{hostname}}:{{port}}

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/status HTTP/1.1

###
GET  {{baseUrl}}/cat

###
GET {{baseUrl}}/cat?name=Jack&color=green
###

###
POST  {{baseUrl}}/cat
content-type: application/json

{
    "name": "Jack",
    "color" : "green"
}

###

POST {{baseUrl}}/cat

<request>
    <name>Alan</name>
    <color>Blue</time>
</request>


###
GET {{baseUrl}}/cat
###

###
GET {{baseUrl}}/cat/1
###

###
POST {{baseUrl}}/cat
content-type: application/json

{
    "name" : "JOHN",
    "color" : "black",
    "description" : "john description"
}
###

###
PUT {{baseUrl}}/cat/1
content-type: application/json

{
    "id" : 1,
    "name" : "JOHN",
    "color" : "white",
    "description" : "john description"
}
###
DELETE  {{baseUrl}}/cat/2

###