@hostname = 127.0.0.1
@port = 3000
@serverUrl = http://{{hostname}}:{{port}} 
@baseUrl = http://{{hostname}}:{{port}}

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/status HTTP/1.1

###
GET  {{baseUrl}}/cat

###
GET {{baseUrl}}/cat?name=Jack&color=green
###

###
POST  {{baseUrl}}/cat
content-type: application/json

{
    "name": "Jack",
    "color" : "green"
}

###

POST {{baseUrl}}/cat

<request>
    <name>Alan</name>
    <color>Blue</time>
</request>
