@hostname = 127.0.0.1
@port = 3000
@serverUrl = http://{{hostname}}:{{port}} 
@baseUrl = http://{{hostname}}:{{port}}

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/status HTTP/1.1

###
GET  {{baseUrl}}/cat

###
GET {{baseUrl}}/cat?name=Jack&color=green
###

###
POST  {{baseUrl}}/cat
content-type: application/json

{
    "name": "Jack",
    "color" : "green"
}

###

POST {{baseUrl}}/cat

<request>
    <name>Alan</name>
    <color>Blue</time>
</request>


###
GET {{baseUrl}}/cat
###

###
GET {{baseUrl}}/cat/4
###

###
GET {{baseUrl}}/cat/4/profile
###

###
POST {{baseUrl}}/cat
content-type: application/json

{
    "name" : "JOHN",
    "color" : "black",
    "description" : "john description",
    "profile" : {
        "father" : "Brown",
        "mother" : "Patty"
    },
    "foods" : [
        {
            "name" : "MIO",
            "type" : "Main Food"
        },
        {
            "name" : "MIO Creamey",
            "type" : "Snack"
        }
    ]
}
###

PUT {{baseUrl}}/cat/4
content-type: application/json

{
    "id" : 4,
    "name" : "JOHN",
    "color" : "white",
    "description" : "john description"
}
###
DELETE  {{baseUrl}}/cat/2
###


POST {{baseUrl}}/auth/login
content-type: application/json


{
    "username" : "john",
    "password" : "changeme11"
}

###

GET {{baseUrl}}/auth/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwMjI4OTUzNCwiZXhwIjoxNzAyMjg5NTk0fQ.dNwedqseu8uFBEEWxiwYcYkRIv2m4kqGkM5BNsxgIzA